import { UserMongooseRepository } from "@/repositories/mongoose4/user-repository";
import { UserRepository } from "@/repositories/interface/user-repository";
import { SensorTypeMongooseRepository } from "@/repositories/mongoose4/sensor-type-repository";
import { SensorTypeRepository } from "@/repositories/interface/sensor-type-repository";
import { SensorRepository } from "@/repositories/interface/sensor-repository";
import { PumpRepository } from "@/repositories/interface/pump-repository";
import { PumpHistoricalRepository } from "@/repositories/interface/pump-historical-repository";
import { MeasureRepository } from "@/repositories/interface/measure-repository";
import { EnvironmentRepository } from "@/repositories/interface/environment-repository";
import { SensorMongooseRepository } from "@/repositories/mongoose4/sensor-repository";
import { PumpMongooseRepository } from "@/repositories/mongoose4/pump-repository";
import { PumpHistoricalMongooseRepository } from "@/repositories/mongoose4/pump-historical-repository";
import { MeasureMongooseRepository } from "@/repositories/mongoose4/measure-repository";
import { EnvironmentMongooseRepository } from "@/repositories/mongoose4/environment-repository";

export const userRepository: UserRepository = new UserMongooseRepository();
export const sensorTypeRepository: SensorTypeRepository = new SensorTypeMongooseRepository();
export const sensorRepository: SensorRepository = new SensorMongooseRepository();
export const pumpRepository: PumpRepository = new PumpMongooseRepository();
export const pumpHistoricalRepository: PumpHistoricalRepository = new PumpHistoricalMongooseRepository();
export const measureRepository: MeasureRepository = new MeasureMongooseRepository();
export const environmentRepository: EnvironmentRepository = new EnvironmentMongooseRepository();
