import { UserMongooseRepository } from "./mongoose4/user-repository";
import { UserRepository } from "./interfaces/user-repository";
import { SensorTypeMongooseRepository } from "./mongoose4/sensor-type-repository";
import { SensorTypeRepository } from "./interfaces/sensor-type-repository";
import { SensorRepository } from "./interfaces/sensor-repository";
import { PumpRepository } from "./interfaces/pump-repository";
import { PumpHistoricalRepository } from "./interfaces/pump-historical-repository";
import { MeasureRepository } from "./interfaces/measure-repository";
import { EnvironmentRepository } from "./interfaces/environment-repository";
import { SensorMongooseRepository } from "./mongoose4/sensor-repository";
import { PumpMongooseRepository } from "./mongoose4/pump-repository";
import { PumpHistoricalMongooseRepository } from "./mongoose4/pump-historical-repository";
import { MeasureMongooseRepository } from "./mongoose4/measure-repository";
import { EnvironmentMongooseRepository } from "./mongoose4/environment-repository";

export const userRepository: UserRepository = new UserMongooseRepository();
export const sensorTypeRepository: SensorTypeRepository = new SensorTypeMongooseRepository();
export const sensorRepository: SensorRepository = new SensorMongooseRepository();
export const pumpRepository: PumpRepository = new PumpMongooseRepository();
export const pumpHistoricalRepository: PumpHistoricalRepository = new PumpHistoricalMongooseRepository();
export const measureRepository: MeasureRepository = new MeasureMongooseRepository();
export const environmentRepository: EnvironmentRepository = new EnvironmentMongooseRepository();
